### ISSUE TITLE
Ability to pass styles prop or style object

### ISSUE THREAD

**Issue by hjelmeir** [krasimir/react-place#2]
Could you add the ability to pass a style prop to your component? My app doesn't have css files included, everything is using inline style objects.

**Comment by krasimir** [comment]
Yep, totally doable. I'll let you know when it's done.

**Comment by krasimir** [comment]
`0.5.1` released and you can pass a `style` property. For example:

``` jsx
location = ReactDOM.render(
  <Location
    className='location'
    placeholder='Where are you?'
    country={ country.value }
    noMatching='Sorry, I can not find {{value}}.'
    onLocationSet={ onLocationSet }
    style={ { color: '#0099FF' } }
    />,
  container
);
```
